javaparser/javasymbolsolver

.gitignore, java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserClassDeclaration.java, java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserEnumConstantDeclaration.java, java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserEnumDeclaration.java, java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserFieldDeclaration.java, java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserInterfaceDeclaration.java, java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserMethodDeclaration.java, java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserParameterDeclaration.java, java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserSymbolDeclaration.java, java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserTypeParameter.java, java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserTypeVariableDeclaration.java
Also changed member ```fieldDeclaration``` in JavaParserFieldDeclaration.java to ```wrappedNode``` for consistency. This fixes something for issue #6.
=> Add getWrappedNode() function to JavaParser___Declaration objects

java-symbol-solver-core/src/test/resources/javaparser_src/generated/com/github/javaparser/ParseException.java, java-symbol-solver-core/src/test/resources/javaparser_src/generated/com/github/javaparser/TokenMgrError.java, java-symbol-solver-core/src/test/resources/javaparser_src/proper_source/com/github/javaparser/ast/comments/CommentsParser.java, java-symbol-solver-model/src/main/java/me/tomassetti/symbolsolver/model/typesystem/ReferenceTypeUsage.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1149 - “Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used ”. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1149
Please let me know if you have any questions.
Ayman Abdelghany.
=> [squid:S1149] Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used

java-symbol-solver-core/pom.xml, java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/reflectionmodel/ReflectionClassDeclaration.java, java-symbol-solver-core/src/test/java/me/tomassetti/symbolsolver/reflectionmodel/ReflectionClassDeclarationTest.java, java-symbol-solver-examples/pom.xml, java-symbol-solver-logic/pom.xml, java-symbol-solver-logic/src/main/java/me/tomassetti/symbolsolver/logic/AbstractClassDeclaration.java, java-symbol-solver-model/pom.xml, pom.xml
Getting all fields always went into a stack overflow, because getting all superclasses or ancestor would loop. It would keep adding "Object" as the ancestor of anything, including Object, then asking for all ancestors, meaning Object, which contained Object again, thereby looping.
=> Stackoverflow fix

java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/contexts/LambdaExprContext.java, java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserMethodDeclaration.java, java-symbol-solver-core/src/test/java/me/tomassetti/symbolsolver/resolution/javaparser/contexts/LambdaExprContextTest.java, java-symbol-solver-core/src/test/resources/Lambda.java.txt
added implementation for contexts other than method calls and implemented tests for newly supported cases.
=> Expand LambdaExprContext to solve more lambda parameter types

java-symbol-solver-core/src/test/java/me/tomassetti/symbolsolver/resolution/AnalyseJavaParserTest.java
* Fixed comparison of expected and generated output of the AnalyzeJavaParserTests for Windows.
* Reduced long term memory consumption of these tests.
=> Fixed tests on windows

README.md
We need to update the Readme to reflect the fact JavaSymbolSolver is now part of JavaParser.
@matozoid @mlangkabel comments on this one?
=> issue101: updating the Readme

java-symbol-solver-core/build.gradle, java-symbol-solver-core/pom.xml, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/SourceFileInfoExtractor.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/CompilationUnitContext.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionClassDeclarationTest.java, java-symbol-solver-examples/build.gradle, java-symbol-solver-examples/pom.xml, java-symbol-solver-logic/build.gradle, java-symbol-solver-logic/pom.xml, java-symbol-solver-model/build.gradle, java-symbol-solver-model/pom.xml
Updating this for Javaparser 3.0.0-RC.4 as it's the one now on Maven central. I had to change the `ImportDeclaration`s back to the single node version, other than that most changes were minor
=> Update for Javaparser 3.0.0-RC.4

java-symbol-solver-core/build.gradle, java-symbol-solver-core/pom.xml, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/MethodCallExprContext.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/ContextTest.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/GenericsResolutionTest.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/StatementContextResolutionTest.java, java-symbol-solver-examples/build.gradle, java-symbol-solver-examples/pom.xml, java-symbol-solver-logic/build.gradle, java-symbol-solver-logic/pom.xml, java-symbol-solver-model/build.gradle, java-symbol-solver-model/pom.xml
Further to #130, pushing this to `3.0.0` (non *release-candidate* version) with very few changes needed.
=> Update for JavaParser 3.0.0

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/javaparsermodel/ConvertToUsageTest.java, java-symbol-solver-core/src/test/resources/LocalTypeDeclarations.java.txt
Fixes very small bug on `convertToUsage` which caused `super` wildcard bounds to be created as `extends` (and added an accompanying test).
eg.
`
Class<? super Number> c;
`
Resolves to:
`java.util.Class<? extends java.lang.Number>`
=> Fixed issue when converting wildcard type with super bound

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/ReferenceTypeImpl.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/model/typesystem/ReferenceTypeTest.java
The `isAssignableBy` method in `ReferenceTypeImpl` does not consider boxing followed by widening reference conversion.
ie. int -> Integer -> Number
For example doing `JavaParserFacade.get(combinedTypeSolver).getType(methodCallExpr);` (on the `foo(1)` method call) throws an error `Method 'foo' cannot be resolved in context ...`
```java
void foo(Number a){
System.out.println("Run.");
}
void bar(){
foo(1);
}
```
Added a fix for this plus a test. (We could arguably get rid of `isCorrespondingBoxingType` but I just kept it in case it returns faster for the common case)
=> Fix issue with reference type assignability to boxed type

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/DefaultVisitorAdapter.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/TypeExtractor.java
Hello again,
I'm submitting a PR to refactor the gigantic `getTypeConcrete` method in the `JavaParserFacade` by using the visitors from JavaParser so that each expression now is split nicely into it's own method.
As a side benefit of the refactoring my IDE now also highlighted some lines which were invalid. In fact lines [493-507](https://github.com/javaparser/javasymbolsolver/blob/07d522aaacf4dfeba0e94d6ac64c9b4d06b825f6/java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.java#L493) in the original `JavaParserFacade` are illegal since the original condition is that `node instanceof MethodReferenceExpr`. I've removed them and the tests still pass, but @ftomassetti if you can have a look and add them back if needed in a proper way would …
=> Refactored out huge method from facade to visitor

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/TypeExtractor.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/MethodResolutionLogic.java
There are quite a few issues with solving methods with generics I'll try and fix the ones I can over the next few days and submit issues for the rest.
As a start nested parameterizations don't work for more than one depth 
```java
class Foo {
<R> R bar(List<R> arg) {
return null;
}
<R> R bar(List<List<R>> arg) {
return null;
}
void test(){
List<List<Integer>> l1;
List<Integer> l2;
bar(l1);  // fails
bar(l2); // works
}
}
```
Hopefully this fixes it
=> Nested type variable assignability fix

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/JavaParserTypeDeclarationAdapter.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserClassDeclaration.java, java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/declarations/ReferenceTypeDeclaration.java
Referencing issue #163 
When traversing the jdk java files, the symbol solver is stuck on resolving the type Object. As Object seems to have the ancestor Object, an infinite loop is created. I modified the relevant passages to get the solver to work. Please let me know if these solutions need improvement or are wrong.
=> Add object type check to avoid infinite ancestor recursion

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserClassDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserConstructorDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserEnumDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserInterfaceDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserMethodDeclaration.java
I was working with a `JavaParserClassDeclaration` object when i saw that i couldn't get access modifier from this object. It can be obtained from JavaParser, but you probably created this method to wrap that ?
`JavaParserFieldDeclaration` already has this `accessLevel()` returning the access specifier. I just updated the method in `JavaParserClassDeclaration`, `JavaParserConstructorDeclaration`, `JavaParserEnumDeclaration`, `JavaParserInterfaceDeclaration`, `JavaParserMethodDeclaration`.
=> Getting access modifiers

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/TypeExtractor.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/CompilationUnitContext.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/JavaParserTypeDeclarationAdapter.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/LambdaExprContext.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/MethodCallExprContext.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/ReferenceTypeImpl.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionClassDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionEnumDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionInterfaceDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionMethodResolutionLogic.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/MethodResolutionLogic.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/logic/InferenceContextTest.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/model/typesystem/ReferenceTypeTest.java, java-symbol-solver-logic/src/main/java/com/github/javaparser/symbolsolver/logic/InferenceContext.java, java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/LambdaConstraintType.java, java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/ReferenceType.java, java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/Type.java, java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/TypeVariable.java
PR for the issues we were discussing before plus some other fixes I was working on for generic types.
Among others this fixes:
1. The substitution of type variables wasn't being performed properly so for example:
```java
List<String> list;
list.stream().map(x -> x.codePoints()); // resolved as Stream<String> incorrectly, should be Stream<IntStream>
```
2. Issues with reflection interfaces only resolving methods in the current interface
```java
List<String> list;
list.toString(); // error - can't be resolved
```
3. Some issues when selecting variadic vs non-variadic in most specific method selection
4. Some general issues with type inference
=> Type system changes

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/TypeExtractor.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/LambdaExprContext.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/LambdaResolutionTest.java, java-symbol-solver-core/src/test/resources/Lambda.java.txt, java-symbol-solver-logic/src/main/java/com/github/javaparser/symbolsolver/logic/InferenceContext.java, java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/PrimitiveType.java, java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/parametrization/TypeParametersMap.java
Hello again,
This fixes a few issues with resolving lambda arguments. The implicit type of a lambda parameter used to be guessed based on the first generic argument of the functional interface (completely ignoring bifunctions or out-of-expected order ones). See 1016f42321316f6b6bd0e7f4cb51ee5958e01153 for more details.
=> Fix issues with lambdas

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/JavaParserTypeDeclarationAdapter.java
For example: This exception is thrown by `internalTypes()` when an ancestor is a JavassistClassDeclaration.
=> Ignore UnsupportedOperationException when solving type in a type's ancestor

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/Helper.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserAnnotationDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserClassDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserEnumDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserInterfaceDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserTypeAdapter.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserTypeVariableDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistClassDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistEnumDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistInterfaceDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionClassDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionEnumDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionInterfaceDeclaration.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserClassDeclarationTest.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserEnumDeclarationTest.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserInterfaceDeclarationTest.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistClassDeclarationTest.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistEnumDeclarationTest.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistInterfaceDeclarationTest.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionClassDeclarationTest.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionEnumDeclarationTest.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/DefaultPackageTest.java, java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/declarations/MethodLikeDeclaration.java, java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/declarations/TypeDeclaration.java, java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/declarations/TypeParameterDeclaration.java
Fixes #190
The methods in `Helper` are mostly the same, just split between two methods now. The biggest difference is that I added support for `EnumDeclaration`.
I left `getPackageName()`/`getClassName()` as unsupported for `TypeParameterDeclaration` as the qualified name refers to its container, not the type of the parameter itself.
I'd also like to point out that in the Javassist classes, I added `.replace('$', '.')` to `getQualifiedName()` as it appeared to be missing for Interfaces and Enums. Let me know if there is a reason that it was missing and I can revert that change.
=> Issue 190: Access package and class names separately in type declaration

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/TypeExtractor.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionMethodResolutionLogic.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/LambdaResolutionTest.java, java-symbol-solver-core/src/test/resources/LambdaMulti.java.txt
Add support for lambdas with blocks eg.
```
i -> {
return 2;
}
```
```
i -> {
foo();
}
```
```
i -> {
int x;
return foo(x);
}
```
=> Allow inferring types for block lambdas

java-symbol-solver-core/build.gradle, java-symbol-solver-examples/build.gradle, java-symbol-solver-logic/build.gradle, java-symbol-solver-model/build.gradle
Just updated Guava version 18.0 to 21.0. All tests pass on my MacBook Pro running OSX 10.11.6.
=> updated Guava version from 18.0 to 21.0

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/TypeExtractor.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/StatementContext.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/TryWithResourceContext.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/Issue200.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/LambdaResolutionTest.java, java-symbol-solver-core/src/test/resources/Issue200.java.txt
Hopefully fixes the issues listed in #200.
There will still be some edge cases where there are different branches returning different types but we would need to rethink the whole way that JSS resolves types and adopt a constraint reduction type system like the one Java uses (https://docs.oracle.com/javase/specs/jls/se8/html/jls-18.html) to deal with those issues. For most cases this should be enough now
=> Issues with try/catch statements inside lambda blocks

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/MethodCallExprContext.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/javaparser/contexts/MethodCallExprContextResolutionTest.java, java-symbol-solver-core/src/test/resources/MethodCalls.java.txt, java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/methods/MethodUsage.java, java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/parametrization/TypeParametersMap.java
The status quo is that the typeParametersMap in MethodUsage is usually empty. This commit fixes things up so that it at least has a chance of being right in the result of solveMethodAsUsage (for the case where a method call has type args).
I think that there is probably still a lot of work to be done to make the method resolution logic 100% correct, but this is probably a step in the right direction.
=> Make the MethodUsage type param map correct in more cases

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/UnsolvedSymbolException.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistClassDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistEnumDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistInterfaceDeclaration.java
Fix proposal regarding the error `Unable to calculate the type of a parameter of a method call` that occurs with static internal classes/enums/interfaces retrieved with `Javassist`. Also added a link to the right `UnsolvedSymbolException` in the deprecated one and updated some of the unsupported operations in `Javassist*Declaration`.
See #112
=> Fix proposal regarding the error with static internal classes/enums/interfaces

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/JavaParserTypeDeclarationAdapter.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserInterfaceDeclaration.java
I think I've found and fixed two more places where infinite recursion can occur in java symbol solver.  At the very least, I tracked down infinite recursions in my runs to these lines and these changes fixed them for me.  It makes since that you shouldn't recurse onto yourself.  The better question might be why self is an ancestor by getAncestors, but I couldn't find a clear way to detect/fix that since the classes weren't the same, which is why I went down this route.
=> Fix Infinite Recursion

build.gradle
See also http://stackoverflow.com/questions/34377367/why-is-gradle-install-replacing-my-version-with-unspecified.
=> Fixed #218, where ./gradlew install set the version to "unspecified"

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistConstructorDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistEnumDeclaration.java
This PR implements the missing `getAncestors()` in `JavassistEnumDeclaration` and `accessLevel()` in `JavassistConstructorDeclaration`. `getAncestors()` only returns direct ancestors as written in the corresponding interface.
java.lang.Enum is also added in the list as the only ancestor class of the enum.
=> Implementation of getAncestors() in JavassistEnumDeclaration

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserInterfaceDeclaration.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/Issue232.java, java-symbol-solver-core/src/test/resources/Issue232.java.txt
This adds a testcase for #232 and resolves the issue by using LazyType in JavaParserInterfaceDeclaration like it is used in JavaParserClassDeclaration.
=> solve issue #232

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFactory.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/Issue235.java, java-symbol-solver-core/src/test/resources/Issue235.java.txt
The problem was that JavaParserFactory.getContext() didn't checked if a ObjectCreationExpr was visited from its type branch or from its class body branch.
I guess the type branch is outside of the scope of the class and belongs to the parent scope. I can't find this in the JLS, but my tests with the compiler prove my assumption:
```java
interface Test { }
...
new Test<X>() { // <- X is undefined
class X { }
};
```
=> fix issue #235

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.java
It's useful to have weak references of TypeSolver**s**  in the static 'instances'. So, the TypeSolver-->JavaParserFacade entries will be garbage-collected automatically and it's not necessary to call 'clearInstances' explicitly.
=> Use a WeakHashMap to avoid memory leaks in JavaParserFacade.instances

java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/Issue228.java, java-symbol-solver-logic/src/main/java/com/github/javaparser/symbolsolver/logic/InferenceContext.java
fixed by considering the case where both, the parameter type and the argument type is a primitive type while inferring types for type parameters. Also created a test that covers this case.
=> fix issue #228 

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFactory.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserAnnotationDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserAnonymousClassDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserClassDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserEnumDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserFieldDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserInterfaceDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserMethodDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserTypeAdapter.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserTypeParameter.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserTypeVariableDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistTypeDeclarationAdapter.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistTypeParameter.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionClassAdapter.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionClassDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionEnumDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionInterfaceDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionMethodResolutionLogic.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionTypeParameter.java, java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/DefaultPackageTest.java, java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/declarations/TypeDeclaration.java, java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/declarations/TypeParameterDeclaration.java
* added `toTypeDeclaration` method to JavaParserFactory to remove code duplications.
* implemented containerType method for most of the types that implement TypeDeclaration
=> Implement containerType methods for TypeDeclarations 

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistClassDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistEnumDeclaration.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistInterfaceDeclaration.java
* until now the method returned Foo$Bar for a type Bar declared inside a type Foo but Foo should only be part of the QualifiedName
=> fixed implemetation of getName method for Javassist type declarations

build.gradle
Systems that don't have UTF-8 as a default system encoding will fail on the compilation of `com.github.javaparser.symbolsolver.resolution.typeinference.BoundSet.thereIsSomeJSuchThatβequalAlphaJ` . This commit forces that UTF-8 is used for the compilation of java sources and for generating javadoc for those sources. An overview of the relevant javadoc parameters here: https://stackoverflow.com/a/1319706 .
=> Add settings to all subprojects to force java compilation and javadoc generation to UTF-8

java-symbol-solver-testing/build.gradle
Make sure Jacoco picks up the sources of the -model, -logic, -core subprojects when analysing coverage in the -testing subproject. Previously, Jacoco would generate an empty coverage report, because it would only take into account the sources of -testing itself (it has none). This ensures that next to the projects' own sources, extra sources are taken into account for coverage. 
This is a partial fix for #79, in that local coverage is now available. Additional work would be necessary to also push coverage to coveralls.io.
Please note that if the project hierarchy or testing setup is ever revised, this would need revision. In particular, if -core, -model, or -logic get their own tests, special care will be needed to aggregate the coverage on parent-level.
=> Jacoco coverage should include sibling project sources

java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/AbstractJavaParserContext.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/FieldAccessContext.java, java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/MethodCallExprContext.java, java-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue300.java, java-symbol-solver-testing/src/test/resources/issue300/Issue300.java
Fix issues #300 and #355.
The logic to get the `ResolvedReferenceTypeDeclaration`'s from a scope and a `TypeSolver` was extracted from `MethodCallExprContext.solveMethod`  to a method named `findTypeDeclarations` and pulled up to `AbstractJavaParserContext` class. After that a method called `FieldAccessContext.solveField` was created. This method uses the `findTypeDeclarations` method mentioned before.
=> Fix issues #300 and #355: Getting the FieldDeclaration from a FieldAccessExpr
