- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/JavaParserFactory.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarators/NoSymbolDeclarator.java
> NoSimbolDeclarator renamed to NoSymbolDeclarator

- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/contexts/ClassOrInterfaceDeclarationContext.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserEnumDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserMethodDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/reflectionmodel/ReflectionMethodResolutionLogic.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/resolution/MethodResolutionLogic.java
- java-symbol-solver-model/src/main/java/me/tomassetti/symbolsolver/model/typesystem/ReferenceTypeUsage.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1155 - “Collection.isEmpty() should be used to test for emptiness”. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1155
Please let me know if you have any questions.
Ayman Abdelghany.
> [squid:S1155] Using Collection.isEmpty() to test for emptiness

- java-symbol-solver-core/walkmod.xml
- java-symbol-solver-examples/walkmod.xml
- java-symbol-solver-logic/walkmod.xml
- java-symbol-solver-model/walkmod.xml
- walkmod.xml
Hi Federico,
I have seen that your walkmod configuration is outdated and thus, invalid. I have upgraded it to take profit of WalkmodHub.
> correct walkmod cfg

- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserClassDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javassistmodel/JavassistClassDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/reflectionmodel/ReflectionClassDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/reflectionmodel/ReflectionInterfaceDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/resolution/MethodResolutionLogic.java
- java-symbol-solver-core/src/test/resources/javaparser_src/proper_source/com/github/javaparser/ast/visitor/ModifierVisitorAdapter.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1066 - “Collapsible "if" statements should be merged”. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1066
Please let me know if you have any questions.
Ayman Abdelghany.
> [squid:S1066] Merging collapsible if statements increases the code's readability

- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserClassDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserEnumDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserInterfaceDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserTypeParameter.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserTypeVariableDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javassistmodel/JavassistClassDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javassistmodel/JavassistInterfaceDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/reflectionmodel/ReflectionClassDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/reflectionmodel/ReflectionInterfaceDeclaration.java
- java-symbol-solver-model/src/main/java/me/tomassetti/symbolsolver/model/declarations/TypeDeclaration.java
Can't get Gradle to install a snapshot, so I'll leave the testing of this code to you :)
This is about https://github.com/ftomassetti/java-symbol-solver/issues/32
> Add GetAllFields

- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/contexts/FieldAccessContext.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserClassDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserEnumDeclaration.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/declarations/JavaParserInterfaceDeclaration.java
Implemented the crude solution given in #45 but refined it to a more elegant solution in second commit.
> Refined solving symbol in FieldAccessContext. #45

- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/JavaParserFacade.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/contexts/MethodCallExprContext.java
- java-symbol-solver-core/src/test/java/me/tomassetti/symbolsolver/resolution/ContextTest.java
- java-symbol-solver-core/src/test/java/me/tomassetti/symbolsolver/resolution/FieldsTest.java
- java-symbol-solver-core/src/test/java/me/tomassetti/symbolsolver/resolution/MethodsTest.java
- java-symbol-solver-core/src/test/resources/AccessThroughSuper.java.txt
- java-symbol-solver-core/src/test/resources/ArrayAccess.java.txt
> Implemented solving method calls on ArrayAccessExpr and SuperExpr.

- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/contexts/MethodCallExprContext.java
- java-symbol-solver-core/src/test/java/me/tomassetti/symbolsolver/resolution/javaparser/contexts/MethodCallExprContextTest.java
- java-symbol-solver-core/src/test/resources/MethodCalls.java.txt
And implemented test for this case.
> Fixed StackOverflowError when solving call on method return type. Issue #43

- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/model/typesystem/ReferenceTypeUsageImpl.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/resolution/MethodResolutionLogic.java
- java-symbol-solver-core/src/test/java/me/tomassetti/symbolsolver/resolution/GenericsTest.java
- java-symbol-solver-core/src/test/resources/GenericCollectionWithExtension.java.txt
- java-symbol-solver-logic/src/main/java/me/tomassetti/symbolsolver/logic/GenericTypeInferenceLogic.java
- java-symbol-solver-model/src/main/java/me/tomassetti/symbolsolver/model/typesystem/ReferenceTypeUsage.java
- java-symbol-solver-model/src/main/java/me/tomassetti/symbolsolver/model/typesystem/TypeUsage.java
* implemented method resolution check if parameters are compatible in case where the expected type is type variable 
* added test for this case
* fixed index out of bounds exception in GenericTypeInferenceLogic
> Method resolution fixes

- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/contexts/ClassOrInterfaceDeclarationContext.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/javaparsermodel/contexts/MethodCallExprContext.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/resolution/MethodResolutionLogic.java
- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/resolution/typesolvers/JarTypeSolver.java
Hi,
Some unused imports and variables are removed.
> unused code removed

- java-symbol-solver-core/src/main/java/me/tomassetti/symbolsolver/resolution/typesolvers/JavaParserTypeSolver.java
> issue73: cache parse java files in JavaSymbolSolver

- java-symbol-solver-core/src/test/java/me/tomassetti/symbolsolver/reflectionmodel/ReflectionMethodDeclarationTest.java
- java-symbol-solver-model/src/main/java/me/tomassetti/symbolsolver/model/declarations/MethodDeclaration.java
> issue77: add qualified name to MethodDeclaration

- README.md
README still contained an old file name. This is now changed to 'ReflectionTypeSolver'.
> changed JreTypeSolver to ReflectionTypeSolver

- README.md
Small change in the README.MD to reflect the current state of the project.
> TypeUsage is now Type

- .gitignore
- java-symbol-solver-core/build.gradle
- java-symbol-solver-core/pom.xml
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionClassDeclarationTest.java
- java-symbol-solver-examples/build.gradle
- java-symbol-solver-examples/pom.xml
- java-symbol-solver-logic/build.gradle
- java-symbol-solver-logic/pom.xml
- java-symbol-solver-model/build.gradle
- java-symbol-solver-model/pom.xml
Add support for JavaParser 3.1.0
> Move to JavaParser 3.1.0

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/CompilationUnitContext.java
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/ContextTest.java
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/DefaultPackageTest.java
> implement resolution of classes from the default package #issue16

- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/LambdaResolutionTest.java
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/MethodsResolutionTest.java
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/VariadicResolutionTest.java
- java-symbol-solver-core/src/test/resources/Lambda.java.txt
- java-symbol-solver-core/src/test/resources/MethodCalls.java.txt
I'm not sure if I've put the tests in the right test classes so feel free to move them around
> Add tests for changes in #172 (closes #173)

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/TypeExtractor.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/MethodCallExprContext.java
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/Issue186.java
- java-symbol-solver-core/src/test/resources/Issue186.java.txt
- java-symbol-solver-logic/src/main/java/com/github/javaparser/symbolsolver/logic/InferenceContext.java
- java-symbol-solver-logic/src/main/java/com/github/javaparser/symbolsolver/logic/InferenceVariableType.java
Fix for the issue described in #186 + Added test
> Fix for lambda issue #186

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/TypeExtractor.java
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/Issue186.java
- java-symbol-solver-core/src/test/resources/Issue186.java.txt
- java-symbol-solver-logic/src/main/java/com/github/javaparser/symbolsolver/logic/InferenceContext.java
Hopefully this fixes a few more errors in #186
> Lambda fixes for #186

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/TypeExtractor.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionMethodResolutionLogic.java
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/Issue156.java
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/LambdaResolutionTest.java
- java-symbol-solver-core/src/test/resources/Issue156.java.txt
- java-symbol-solver-core/src/test/resources/LambdaMulti.java.txt
Possible fix for the field access issues in #156. 
Not sure if this resolves everything but it should help.
Should merge after #192 to avoid conflicting
> Possible fix for Issue #156

- java-symbol-solver-core/build.gradle
- java-symbol-solver-logic/build.gradle
- java-symbol-solver-model/build.gradle
Pain-free move to JavaParser 3.2.0
> Move to JavaParser 3.2.0

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/typesolvers/JavaParserTypeSolver.java
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/SymbolSolverTest.java
- java-symbol-solver-core/src/test/resources/javaparser_new_src/javaparser-core/com/github/javaparser/PackageLocalClasses.java
> In JavaParserTypeSolver, don't assume that class Foo is in a file named Foo.java

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/TypeExtractor.java
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/javaparsermodel/DifferentiateDotExpressionTest.java
- java-symbol-solver-core/src/test/resources/differentiate_dot_expressions/FieldDotExpressions.java
- java-symbol-solver-core/src/test/resources/differentiate_dot_expressions/InnerClassDotExpressions.java
- java-symbol-solver-core/src/test/resources/differentiate_dot_expressions/PackageDotExpressions.java
- java-symbol-solver-core/src/test/resources/differentiate_dot_expressions/com/packageName/ClassInPackage.java
- java-symbol-solver-core/src/test/resources/differentiate_dot_expressions/com/packageName/InnerClassContainer.java
- java-symbol-solver-core/src/test/resources/differentiate_dot_expressions/com/packageName/InnerClassFieldContainer.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/declarations/TypeDeclaration.java
Fixes [Issue 208](https://github.com/javaparser/javasymbolsolver/issues/208).
> Issue 208: Various dot expressions cannot be solved for method calls

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/TypeExtractor.java
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/javaparsermodel/DifferentiateDotExpressionTest.java
- java-symbol-solver-core/src/test/resources/differentiate_dot_expressions/InnerStaticClassFieldDotExpressions.java
- java-symbol-solver-core/src/test/resources/differentiate_dot_expressions/com/packageName/InnerStaticClassFieldContainer.java
R: @ftomassetti , let me know if it makes sense.
> Fixed #215, Integer.parseInt(ClassX.ClassY.MY_INT) not properly resolved.

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/MethodCallExprContext.java
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/javaparser/declarations/JavaParserTypeParameterResolutionTest.java
- java-symbol-solver-core/src/test/resources/GenericMethodArguments.java.txt
This is a follow up PR on issue #183. 
While I'm not sure it solves all the problems pertaining to the phenomena described, it does solve a few (see the added tests), and seems to be an improvement over the status quo.
@3ch0 , I used your suggestion to overcome one of the issues, so please feel free to comment as I realise you wanted to do some more testing. One of the goals of this PR is to share the use cases and accompanying tests.
> Fixes some issues related to issue #183, i.e., type inference for generic methods and arguments.

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistTypeDeclarationAdapter.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistUtils.java
> Fixed #221, where resolving generic method arguments which are inner classes fails.

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/MethodCallExprContext.java
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/resolution/VariadicResolutionTest.java
- java-symbol-solver-core/src/test/resources/MethodCalls.java.txt
> Fixed #224, where variadic static methods with a generic class arg failed to be resolved

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFactory.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/AnonymousClassDeclarationContext.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserAnonymousClassDeclaration.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserMethodDeclaration.java
- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserAnonymousClassDeclarationTest.java
- java-symbol-solver-core/src/test/resources/AnonymousClassDeclarations.java.txt
@ftomassetti , let me know how it looks.
See also #226.
> Fixed issue #226, where anonymous classes were not considered a valid resolution context

- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/Issue251.java
- java-symbol-solver-core/src/test/resources/Issue251.java.txt
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/ReferenceType.java
* added more detailed check of type parameters when comparing two reference types
* added test case for this issue
> Fix issue 251

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistConstructorDeclaration.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistMethodDeclaration.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistTypeDeclarationAdapter.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistTypeParameter.java
> add getContainer method to JavassistTypeParameter

- java-symbol-solver-core/src/test/java/com/github/javaparser/symbolsolver/Issue113.java
- java-symbol-solver-core/src/test/resources/issue113/com/foo/Widget.java
- java-symbol-solver-core/src/test/resources/issue113/com/foo/base/Widget.java
> Adding tests to verify #113 has been corrected

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserTypeParameter.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistTypeParameter.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionTypeParameter.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/declarations/TypeParameterDeclaration.java
* implemented getContainer method for all TypeParameterDeclarations
* allowed all TypeParameterDeclaration to have a ConstructorDeclaration as Container
> refined container logic of TypeParameterDeclarations

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserAnonymousClassDeclaration.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/MethodResolutionLogic.java
* used for solving calls to methods declared in anonymous class declaration
* callees can be other methods declared in said anonymous class declaration
> implemented solving "this" in anonymous class declaration

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/DefaultConstructorDeclaration.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserConstructorDeclaration.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserEnumDeclaration.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserMethodDeclaration.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistConstructorDeclaration.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistEnumDeclaration.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistMethodDeclaration.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionConstructorDeclaration.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionMethodDeclaration.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/declarations/MethodLikeDeclaration.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/declarations/TypeParameterDeclaration.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/declarations/TypeParametrizable.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/methods/MethodUsage.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/resolution/SymbolReference.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/IntersectionType.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/LambdaConstraintType.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/PrimitiveType.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/ReferenceType.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/Type.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/TypeVariable.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/Wildcard.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/parametrization/TypeParameterValueProvider.java
While working on Issue 9 I derived a few changes that can be nerged separately
> Issue9derived1

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/ReferenceTypeImpl.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/ReferenceType.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/Type.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/TypeVariable.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/Wildcard.java
Other improvements backported from the branch on #9
> Issue 9 derived2

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/typeinference/InferenceVariable.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/typeinference/MethodType.java
Extracting from the PR for #9 a couple of simple classes.
They are implemented following the JLS but they are not yet used by the rest of JSS.
> Method type and Inference Variable

- README.md
Common tasks, the need to use wrapper, and a quick note on how gradle works.
Aims to fix issue #289.
> Document gradle usage

- java-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/resolution/MethodsResolutionTest.java
- java-symbol-solver-testing/src/test/resources/Issue338.java.txt
> Verify that type promotion works

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparser/Navigator.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFactory.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/AbstractJavaParserContext.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/FieldAccessContext.java
- java-symbol-solver-model/src/main/java/com/github/javaparser/symbolsolver/model/resolution/TypeSolver.java
- java-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue343.java
and improving error messages for nodes outside the AST
> adding tests for #343 

- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/JavaSymbolSolver.java
- java-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparser/Navigator.java
- java-symbol-solver-model/build.gradle
> Moving to JP 3.5.5.
